MANIFEST: manifest.tab
EXTERNAL_COUNTS_DIR: /net/eichler/vol28/projects/long_read_archive/nobackups/sharing/EEE_Kinnex/1KG/ntsm_count_files
SVDPREFIX:  /net/eichler/vol28/home/yjkwon5/nobackups/git_works/sample_qc/db_source/somaliar_snps.vcf.gz
COMPARE_ONLY_EXT: True
MISMATCH_FLAG: True
