#!/usr/bin/env bash

# Get directory where the script is located
SOURCE="${BASH_SOURCE[0]}"

while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Modules
module load miniconda/4.12.0

# Init
mkdir -p log

# Get jobs
JOB_COUNT=$1

shift

# Run
snakemake -s ${SOURCE_DIR}/Snakefile \
	-j ${JOB_COUNT} \
	--jobname "{rulename}.{jobid}" \
	--drmaa " -V -cwd -j y -o ./log -e ./log -l h_rt={resources.hrs}:00:00 -l mfree={resources.mem}G -pe serial {threads} \
	-l hostname='e023|e024|e025|e026|e027|e028|e029' -l testing=true \
	-w n -S /bin/bash" \
	"$@" \
    --use-singularity  \
    --singularity-args "--bind /net:/net"  \
	--restart-times 1 -w 60 \
	--printshellcmds \
	--keep-going \
	--ri
